CREATE TABLE IF NOT EXISTS USERDATA (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName varchar(64) NOT NULL,
    lastName varchar(64) NOT NULL,
    birthdate DATE NOT NULL,
    email varchar(256) NOT NULL,
    username varchar(64) NOT NULL UNIQUE,
    sport VARCHAR(255) NOT NULL,
    team VARCHAR(255) NOT NULL,
    propic blob
);

CREATE TABLE IF NOT EXISTS USERS (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     username varchar(64) NOT NULL,
     password varchar(256) NOT NULL,
     enabled INT NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(64) NOT NULL,
    authority varchar(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS PREMI (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(256) NOT NULL,
    winner varchar(64)
);

CREATE TABLE IF NOT EXISTS RECENSIONI (
    author varchar(64) PRIMARY KEY,
    text varchar(256),
    rating int NOT NULL,
    publishingDate date NOT NULL,
    CHECK (rating>=1 AND rating<=5)
);

CREATE TABLE IF NOT EXISTS GIORNATE (
    username varchar(64) NOT NULL,
    dateOfPlay DATE NOT NULL DEFAULT CURRENT_DATE,
    points INT NOT NULL,
    PRIMARY KEY (username, dateOfPlay)
);

CREATE TABLE IF NOT EXISTS NEWS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(256) NOT NULL,
    content text NOT NULL,
    date date NOT NULL
);

insert into USERS (USERNAME, PASSWORD, ENABLED)
SELECT * FROM (
    values  ('admin#24', '$2a$10$8gxtF0uC16B3JFe76TFMXuhOpkSc9iKzD1FLAgiJeU2B2raAF.I7e', 1),
            ('moderator#24', '$2a$10$Of3/.ErWUcDIUSY8Iv.5xeE3SbEe9SbeFUkxFtix/alDY9pf3thbO', 1),
            ('user#24', '$2a$10$cPA.RZIWJxZ6pYEKJtU16e93sw54OBTwFjA6.lgqU4Gelfgc9r3zu', 1)
                  ) AS new_users(USERNAME, PASSWORD, ENABLED)
WHERE NOT EXISTS (SELECT 1 FROM USERS LIMIT 1);

insert into AUTHORITIES (USERNAME, AUTHORITY)
SELECT * FROM (
    values  ('admin#24', 'ROLE_ADMIN'),
            ('moderator#24', 'ROLE_MODERATOR'),
            ('user#24', 'ROLE_USER')
                  ) AS new_authorities(USERNAME, AUTHORITY)
WHERE NOT EXISTS (SELECT 1 FROM AUTHORITIES LIMIT 1);

insert into USERDATA (FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL, USERNAME, SPORT, TEAM, PROPIC)
SELECT * FROM (
values  ('Ad', 'Min', '2000-01-01', 'admin@mail.ext', 'admin#24', 'Canottaggio', 'San Francisco', null),
        ('Moder', 'Ator', '2000-01-01', 'moderator@mail.ext', 'moderator#24', 'Canottaggio', 'San Francisco', null),
        ('Us', 'Er', '2000-01-01', 'user@mail.ext', 'user#24', 'Canottaggio', 'San Francisco', null)
                    ) AS new_userdata(FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL, USERNAME, SPORT, TEAM, PROPIC)
WHERE NOT EXISTS (SELECT 1 FROM USERDATA LIMIT 1);

INSERT INTO RECENSIONI (author, text, rating, publishingDate)
SELECT * FROM (
    VALUES
        ('moderator#24', 'Great experience, very exciting!', 5, '2024-01-15'),
        ('user#24', 'Decent service, but could be better.', 3, '2024-01-20')
    ) AS new_reviews(author, text, rating, date)
WHERE NOT EXISTS (SELECT 1 FROM RECENSIONI LIMIT 1);

--  DB RESET
-- DROP TABLE USERDATA;
-- DROP TABLE USERS;
-- DROP TABLE GIORNATE;
-- DROP TABLE AUTHORITIES;
-- DROP TABLE PREMI;
-- DROP TABLE RECENSIONI;
